spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform:
      org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:file:./data
    driverClassName: org.h2.Driver
    password: root
    username: root
  application:
    name: Agenda Lives
  h2:
    console:
      enabled: false
server:
  port: 8080


